"""Pillow-based renderer for infographics.

Produces a clean, modern portrait infographic PNG from a structured spec
so that the feature is available without heavy browser or HTML toolchains.
"""
from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from PIL import Image, ImageDraw, ImageFont

_THEMES = {
    "blue": {"bg": "#0f172a", "panel": "#1e293b", "accent": "#38bdf8", "text": "#f1f5f9",
             "muted": "#94a3b8"},
    "green": {"bg": "#052e16", "panel": "#064e3b", "accent": "#4ade80", "text": "#ecfdf5",
              "muted": "#86efac"},
    "orange": {"bg": "#431407", "panel": "#7c2d12", "accent": "#fb923c", "text": "#fff7ed",
               "muted": "#fdba74"},
    "mono": {"bg": "#111827", "panel": "#1f2937", "accent": "#f3f4f6", "text": "#f9fafb",
             "muted": "#9ca3af"},
}


def _font(size: int, bold: bool = False) -> ImageFont.ImageFont:
    candidates_bold = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    ]
    candidates_regular = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    ]
    paths = candidates_bold if bold else candidates_regular
    for p in paths:
        try:
            return ImageFont.truetype(p, size=size)
        except Exception:
            continue
    return ImageFont.load_default()


def _text_size(draw: ImageDraw.ImageDraw, text: str, font) -> Tuple[int, int]:
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[2] - bbox[0], bbox[3] - bbox[1]


def _wrap(text: str, width: int) -> List[str]:
    return textwrap.wrap(text, width=width) or [""]


def render_infographic(data: Dict[str, Any], path: Path) -> Path:
    theme_name = (data.get("color_theme") or "blue").lower()
    theme = _THEMES.get(theme_name, _THEMES["blue"])

    W, H = 1200, 1800
    img = Image.new("RGB", (W, H), theme["bg"])
    draw = ImageDraw.Draw(img)

    title = data.get("title", "Infographic")
    subtitle = data.get("subtitle", "")
    sections: List[Dict[str, Any]] = data.get("sections") or []
    stats: List[Dict[str, Any]] = data.get("stats") or []

    title_font = _font(58, bold=True)
    subtitle_font = _font(26)
    h_font = _font(30, bold=True)
    body_font = _font(22)
    stat_num_font = _font(54, bold=True)
    stat_label_font = _font(20)

    padding = 60
    y = padding

    for line in _wrap(title, 30):
        draw.text((padding, y), line, font=title_font, fill=theme["accent"])
        _, h = _text_size(draw, line, title_font)
        y += h + 6
    y += 16

    if subtitle:
        for line in _wrap(subtitle, 60):
            draw.text((padding, y), line, font=subtitle_font, fill=theme["muted"])
            _, h = _text_size(draw, line, subtitle_font)
            y += h + 4
        y += 24

    draw.rectangle(
        [(padding, y), (W - padding, y + 4)],
        fill=theme["accent"],
    )
    y += 40

    if stats:
        stats_top = y
        panel_h = 180
        draw.rectangle(
            [(padding, y), (W - padding, y + panel_h)],
            fill=theme["panel"],
        )
        cols = min(len(stats), 4)
        col_w = (W - 2 * padding) // cols
        for i, st in enumerate(stats[:cols]):
            cx = padding + i * col_w + col_w // 2
            value = str(st.get("value", ""))
            label = str(st.get("label", ""))
            v_w, v_h = _text_size(draw, value, stat_num_font)
            draw.text((cx - v_w // 2, y + 36), value, font=stat_num_font,
                      fill=theme["accent"])
            for li, ln in enumerate(_wrap(label, 18)[:2]):
                l_w, l_h = _text_size(draw, ln, stat_label_font)
                draw.text(
                    (cx - l_w // 2, y + 36 + v_h + 10 + li * (l_h + 2)),
                    ln,
                    font=stat_label_font,
                    fill=theme["text"],
                )
        y = stats_top + panel_h + 40

    for sect in sections[:6]:
        heading = sect.get("heading", "")
        body = sect.get("text", "")
        draw.text((padding, y), heading, font=h_font, fill=theme["accent"])
        _, h = _text_size(draw, heading, h_font)
        y += h + 10
        for line in _wrap(body, 70):
            if y + 32 > H - padding:
                break
            draw.text((padding, y), line, font=body_font, fill=theme["text"])
            _, lh = _text_size(draw, line, body_font)
            y += lh + 4
        y += 24
        if y > H - padding - 60:
            break

    footer = "Generated by Open Notebook"
    f_w, f_h = _text_size(draw, footer, stat_label_font)
    draw.text(
        (W - padding - f_w, H - padding - f_h),
        footer,
        font=stat_label_font,
        fill=theme["muted"],
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(str(path), format="PNG")
    return path


def render_infographic_html(data: Dict[str, Any], path: Path) -> Path:
    """Emit a static HTML version of the infographic."""
    theme = (data.get("color_theme") or "blue").lower()
    sections = data.get("sections") or []
    stats = data.get("stats") or []
    bg = _THEMES.get(theme, _THEMES["blue"])

    sections_html = "\n".join(
        f'<section><h2>{s.get("heading", "")}</h2><p>{s.get("text", "")}</p></section>'
        for s in sections
    )
    stats_html = "\n".join(
        f'<div class="stat"><div class="num">{s.get("value", "")}</div>'
        f'<div class="lbl">{s.get("label", "")}</div></div>'
        for s in stats
    )
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"><title>{data.get('title', 'Infographic')}</title>
<style>
  body {{ background: {bg['bg']}; color: {bg['text']}; font-family: -apple-system, system-ui, sans-serif; padding: 48px; }}
  h1 {{ color: {bg['accent']}; font-size: 48px; margin: 0 0 12px; }}
  h2 {{ color: {bg['accent']}; margin-top: 32px; }}
  .stats {{ display: flex; gap: 24px; background: {bg['panel']}; padding: 24px; border-radius: 16px; margin: 24px 0; }}
  .stat {{ flex: 1; text-align: center; }}
  .num {{ font-size: 42px; font-weight: 700; color: {bg['accent']}; }}
  .lbl {{ color: {bg['muted']}; margin-top: 4px; }}
  section {{ background: {bg['panel']}; padding: 16px 24px; border-radius: 12px; margin: 16px 0; }}
</style>
</head>
<body>
<h1>{data.get('title', 'Infographic')}</h1>
<p style="color:{bg['muted']}">{data.get('subtitle', '')}</p>
<div class="stats">{stats_html}</div>
{sections_html}
<footer style="margin-top:48px;color:{bg['muted']};font-size:12px;">Generated by Open Notebook</footer>
</body></html>"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
    return path
